// <auto-generated />
using F1_standings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1_standings.Migrations
{
    [DbContext(typeof(F1Context))]
    [Migration("20240327091328_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("F1_standings.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("driverId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("familyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("givenName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            dateOfBirth = "1996-03-23",
                            driverId = "albon",
                            familyName = "Albon",
                            givenName = "Alexander",
                            nationality = "Thai"
                        },
                        new
                        {
                            Id = 2,
                            dateOfBirth = "1989-08-28",
                            driverId = "bottas",
                            familyName = "Bottas",
                            givenName = "Valtteri",
                            nationality = "Finnish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
